### ISSUE TITLE
这个只有，我有IPV6我才能访问你吧。

### ISSUE THREAD

**Issue by zhou1050** [1015770492/autoPPPOEAndDDNS#1]

**Comment by 1015770492** [comment]
你的表达我没有看懂。
“这个只有，我有IPV6我才能访问你吧”指的是什么意思？

首先前提是确保拨号能得到公网IPV6地址，然后调用工具。

建议你使用，宽带王6.0进行开机自动拨号即可，ddns操作
见文章：
[win10断网重连宽带(宽带王)强烈推荐， 关键词：自动拨号、IPV6、断网自动重连、无网络自动重连](https://blog.csdn.net/qq_41813208/article/details/113920567)

**Comment by 1015770492** [comment]
如果有什么问题可以加我qq：1015770492 这样消息能够被及时的处理

**Comment by TSYMQMYST** [comment]
只有双方都是ipv6才能互相访问.
如果A只有ipv4 是访问不到b的ipv6的

**Comment by 1015770492** [comment]
> 只有双方都是ipv6才能互相访问. 如果A只有ipv4 是访问不到b的ipv6的

宽带拨号能拿到ipv6，只要能访问公网就能用ipv6, ipv6是默认就带的。
